# Generated by Django 5.0.2 on 2025-10-02 20:15

import django.db.models.deletion
import job_portal.apps.attachments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=job_portal.apps.attachments.models.generic_attachment_storage_upload_to, verbose_name='File')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('size', models.PositiveIntegerField(verbose_name='File Size (bytes)')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='File Type')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is Public')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='attachments_content_44d952_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='attachments_uploade_565374_idx'), models.Index(fields=['file_type'], name='attachments_file_ty_cc8c38_idx')],
            },
        ),
    ]
