# Generated by Django 5.0.2 on 2025-06-10 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0002_attachment_original_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=2000, verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Множественный выбор'), ('ordering', 'Упорядочивание'), ('fill_in_the_blanks', 'Заполните пропуски'), ('matching', 'Сопоставление'), ('record_audio', 'Запись аудио')], help_text='Тип вопроса, например, множественный выбор, заполнение пропусков и т.д.', max_length=50, verbose_name='Тип вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос компонент',
                'verbose_name_plural': 'Вопросы компоненты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MatchingElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500, verbose_name='Текст элемента')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching_elements', to='attachments.attachment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_elements', to='questions.question')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок ответа в вопросе. Меньшие числа идут первыми.', verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mc_options', to='questions.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RecordAudioQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название вопроса')),
                ('instructions', models.TextField(help_text='Инструкции для пользователя по записи аудио', verbose_name='Инструкции')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_audio_questions', to='questions.question')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500, verbose_name='Текст элемента')),
                ('correct_order', models.PositiveIntegerField(verbose_name='Правильный порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_items', to='questions.question')),
            ],
            options={
                'ordering': ['correct_order'],
                'unique_together': {('question', 'correct_order')},
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('left_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_pairs', to='questions.matchingelement')),
                ('right_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_pairs', to='questions.matchingelement')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='questions.question')),
            ],
            options={
                'unique_together': {('question', 'left_element', 'right_element')},
            },
        ),
        migrations.CreateModel(
            name='FillInBlankLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(help_text='Use {{BLANK:1}}, {{BLANK:2}}, etc. to mark blank spaces with position numbers', max_length=500, verbose_name='Текст пропуска')),
                ('correct_answer', models.CharField(max_length=500, verbose_name='Правильный ответ')),
                ('correct_answers', models.JSONField(default=list, help_text='List of correct answers in order of blanks.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the blank line in the question. Lower numbers appear first.', verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_in_blanks', to='questions.question')),
            ],
            options={
                'unique_together': {('question', 'text')},
            },
        ),
    ]
