# Generated by Django 5.0.2 on 2025-06-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderingitem',
            unique_together=set(),
        ),
    ]
