# Generated by Django 5.0.2 on 2025-06-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_orderingitem_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fillinblankline',
            options={'ordering': ['order'], 'verbose_name': 'Заполните пропуск', 'verbose_name_plural': 'Заполните пропуски'},
        ),
        migrations.AlterUniqueTogether(
            name='fillinblankline',
            unique_together=set(),
        ),
    ]
