# Generated by Django 5.0.2 on 2025-06-14 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_fillinblankline_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillGapBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField(help_text='Index in the format {{index}} in the question text')),
                ('correct_answers', models.JSONField(default=list, help_text='Accepted answers for this gap (can include multiple variants)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_gap_blanks', to='questions.question')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FillInBlankLine',
        ),
    ]
