# Generated by Django 5.0.2 on 2025-06-17 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_fillgapblank_delete_fillinblankline'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordAudioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название вопроса')),
                ('instructions', models.TextField(help_text='Инструкции для пользователя по записи аудио', verbose_name='Инструкции')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record_audio_settings', to='questions.question')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='RecordAudioQuestion',
        ),
    ]
