# Generated by Django 5.0.2 on 2025-09-24 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sms_notifications', models.BooleanField(default=True, verbose_name='SMS Notifications')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push Notifications')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('task_notifications', models.BooleanField(default=True, verbose_name='Task Notifications')),
                ('specialist_messages', models.BooleanField(default=True, verbose_name='Specialist Messages')),
                ('task_updates', models.BooleanField(default=True, verbose_name='Task Updates')),
                ('marketing_emails', models.BooleanField(default=False, verbose_name='Marketing Emails')),
                ('promotional_sms', models.BooleanField(default=False, verbose_name='Promotional SMS')),
                ('newsletter', models.BooleanField(default=False, verbose_name='Newsletter')),
                ('system_alerts', models.BooleanField(default=True, verbose_name='System Alerts')),
                ('security_notifications', models.BooleanField(default=True, verbose_name='Security Notifications')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='Quiet Hours Enabled')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours Start')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours End')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification Settings',
                'verbose_name_plural': 'User Notification Settings',
            },
        ),
    ]
