# Generated by Django 5.0.2 on 2025-09-12 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_role',
        ),
    ]
