# Generated by Django 5.0.2 on 2025-09-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен для заказов'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='service_categories',
            field=models.JSONField(blank=True, default=list, verbose_name='Категории услуг'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='total_reviews',
            field=models.IntegerField(default=0, verbose_name='Всего отзывов'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_role',
            field=models.CharField(blank=True, choices=[('job_seeker', 'Ищу работу'), ('service_provider', 'Предлагаю услуги')], max_length=20, null=True, verbose_name='Роль пользователя'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
