# Generated by Django 5.0.2 on 2025-06-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='original_name',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='Original Name'),
        ),
    ]
