# Generated by Django 5.0.2 on 2025-10-02 20:15

import django.core.validators
import django.db.models.deletion
import utils.abstract_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('general_opinion', models.JSONField(default=dict, verbose_name='General Opinion')),
                ('detailed_feedback', models.TextField(blank=True, help_text="User's detailed experience description", verbose_name='Detailed Feedback')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('design_feedback', models.BooleanField(default=False, verbose_name='Excellent Design')),
                ('usability_feedback', models.BooleanField(default=False, verbose_name='Hard to Understand')),
                ('bug_report', models.BooleanField(default=False, verbose_name='App Problems')),
                ('missing_features', models.BooleanField(default=False, verbose_name='Missing Functions')),
                ('everything_satisfies', models.BooleanField(default=False, verbose_name='Everything Satisfies')),
                ('app_version', models.CharField(blank=True, max_length=20, verbose_name='App Version')),
                ('device_info', models.CharField(blank=True, max_length=100, verbose_name='Device Info')),
                ('platform', models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20, verbose_name='Platform')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Reviewed by Admin')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Feedback',
                'verbose_name_plural': 'App Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('title', utils.abstract_models.TitleField(max_length=100, verbose_name='Title')),
                ('comment', models.TextField(blank=True, verbose_name='Review Comment')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jobs.job')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='users.master')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'reviewer')},
            },
        ),
    ]
