# Generated by Django 5.0.2 on 2025-09-24 22:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('general_opinion', models.JSONField(default=dict, help_text='Selected options from checkboxes', verbose_name='General Opinion')),
                ('detailed_feedback', models.TextField(blank=True, help_text="User's detailed experience description", verbose_name='Detailed Feedback')),
                ('overall_rating', models.PositiveIntegerField(help_text='Overall app rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Overall Rating')),
                ('design_feedback', models.BooleanField(default=False, verbose_name='Excellent Design')),
                ('usability_feedback', models.BooleanField(default=False, verbose_name='Hard to Understand')),
                ('bug_report', models.BooleanField(default=False, verbose_name='App Problems')),
                ('missing_features', models.BooleanField(default=False, verbose_name='Missing Functions')),
                ('everything_satisfies', models.BooleanField(default=False, verbose_name='Everything Satisfies')),
                ('app_version', models.CharField(blank=True, max_length=20, verbose_name='App Version')),
                ('device_info', models.CharField(blank=True, max_length=100, verbose_name='Device Info')),
                ('platform', models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20, verbose_name='Platform')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Reviewed by Admin')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Feedback',
                'verbose_name_plural': 'App Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
