FROM python:3.11-slim

WORKDIR /home/app

RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.dev.txt .
RUN pip install -r requirements.dev.txt

COPY . .

EXPOSE 8000

ENTRYPOINT ["sh", "./entrypoint.sh"]