FROM python:3.11-slim

WORKDIR /home/app

RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.prod.txt .
RUN pip install -r requirements.prod.txt

COPY . .

RUN python manage.py collectstatic --noinput --settings=backend.settings.prod

EXPOSE 8000

CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "4", "--worker-class", "gevent", "--timeout", "30"]
