# Generated by Django 5.0.2 on 2025-10-02 20:15

import django.db.models.deletion
import utils.abstract_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', utils.abstract_models.TitleField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('contact_phone', utils.abstract_models.PhoneNumberField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('is_active', utils.abstract_models.ActiveField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('works_remotely', models.BooleanField(default=False, verbose_name='Works Remotely')),
                ('accepts_clients_at_location', models.BooleanField(default=False, verbose_name='Accepts Clients at Location')),
                ('travels_to_clients', models.BooleanField(default=True, verbose_name='Travels to Clients')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available for Work')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hourly Rate')),
                ('response_time_hours', models.PositiveIntegerField(default=24, verbose_name='Response Time (hours)')),
                ('work_experience_start_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Work Experience Start Year')),
                ('education_institution', models.CharField(blank=True, max_length=200, verbose_name='Education Institution')),
                ('education_years', models.CharField(blank=True, help_text='e.g., 2005-2009', max_length=20, verbose_name='Education Years')),
                ('languages', models.JSONField(default=list, help_text='List of languages spoken', verbose_name='Languages')),
                ('about_description', models.TextField(blank=True, verbose_name='About Description')),
                ('current_location', models.CharField(blank=True, max_length=200, verbose_name='Current Location')),
                ('is_online', models.BooleanField(default=False, verbose_name='Is Online')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Last Seen')),
                ('is_verified_provider', models.BooleanField(default=False, verbose_name='Verified Provider')),
                ('is_top_master', models.BooleanField(default=False, verbose_name='Top Master')),
                ('service_areas', models.ManyToManyField(blank=True, related_name='providers', to='core.servicearea')),
                ('services_offered', models.ManyToManyField(blank=True, related_name='providers_offering_service', to='core.servicesubcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Master Profile',
                'verbose_name_plural': 'Master Profiles',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('contact_phone', utils.abstract_models.PhoneNumberField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total Orders')),
                ('completed_orders', models.PositiveIntegerField(default=0, verbose_name='Completed Orders')),
                ('cancelled_orders', models.PositiveIntegerField(default=0, verbose_name='Cancelled Orders')),
                ('preferred_services', models.ManyToManyField(blank=True, related_name='employer_preferences', to='core.servicesubcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
                ('favorite_masters', models.ManyToManyField(blank=True, related_name='favorite_employers', to='users.master')),
            ],
            options={
                'verbose_name': 'Employer Profile',
                'verbose_name_plural': 'Employer Profiles',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('name', utils.abstract_models.TitleField(max_length=100, verbose_name='Title')),
                ('issuing_organization', models.CharField(max_length=200, verbose_name='Issuing Organization')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Certificate Number')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.master')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='MasterStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_jobs_completed', models.PositiveIntegerField(default=0, verbose_name='Total Jobs Completed')),
                ('on_time_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='On Time Percentage')),
                ('repeat_customer_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Repeat Customer Percentage')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Average Rating')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Total Reviews')),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='users.master')),
            ],
            options={
                'verbose_name': 'Master Statistics',
                'verbose_name_plural': 'Master Statistics',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('name', utils.abstract_models.TitleField(max_length=100, unique=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', utils.abstract_models.ActiveField(default=True, verbose_name='Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='core.servicecategory')),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Professions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='master',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masters', to='users.profession'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('name', utils.abstract_models.TitleField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', utils.abstract_models.ActiveField(default=True, verbose_name='Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.servicecategory')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('title', utils.abstract_models.TitleField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Item')),
                ('attachments', models.ManyToManyField(blank=True, related_name='portfolio_items', to='attachments.attachment')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='users.master')),
                ('skill_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='users.skill')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20, verbose_name='Proficiency Level')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('is_primary_skill', models.BooleanField(default=False, verbose_name='Primary Skill')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_skills', to='users.master')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='users.skill')),
            ],
            options={
                'verbose_name': 'Master Skill',
                'verbose_name_plural': 'Master Skills',
                'unique_together': {('master', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='master',
            name='skills',
            field=models.ManyToManyField(related_name='masters', through='users.MasterSkill', to='users.skill'),
        ),
    ]
