# Generated by Django 5.0.2 on 2025-09-23 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('service_provider', 'Service Provider'), ('both', 'Both')], default='client', max_length=20, verbose_name='User Type')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, verbose_name='Gender')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Terms Accepted')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Terms Accepted At')),
                ('notification_preferences', models.JSONField(default=dict, verbose_name='Notification Preferences')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Verification Date')),
                ('preferred_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_portal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='Business Name')),
                ('business_description', models.TextField(blank=True, verbose_name='Business Description')),
                ('works_remotely', models.BooleanField(default=False, verbose_name='Works Remotely')),
                ('accepts_clients_at_location', models.BooleanField(default=False, verbose_name='Accepts Clients at Location')),
                ('travels_to_clients', models.BooleanField(default=True, verbose_name='Travels to Clients')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available for Work')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Average Rating')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Total Reviews')),
                ('is_verified_provider', models.BooleanField(default=False, verbose_name='Verified Provider')),
                ('service_areas', models.ManyToManyField(blank=True, related_name='providers', to='core.servicearea')),
                ('services_offered', models.ManyToManyField(blank=True, related_name='providers_offering_service', to='core.servicesubcategory')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profile', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Service Provider Profile',
                'verbose_name_plural': 'Service Provider Profiles',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total Orders')),
                ('completed_orders', models.PositiveIntegerField(default=0, verbose_name='Completed Orders')),
                ('cancelled_orders', models.PositiveIntegerField(default=0, verbose_name='Cancelled Orders')),
                ('preferred_services', models.ManyToManyField(blank=True, related_name='client_preferences', to='core.servicesubcategory')),
                ('favorite_providers', models.ManyToManyField(blank=True, related_name='favorite_clients', to='users.serviceproviderprofile')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
            },
        ),
    ]
