# Generated by Django 5.0.2 on 2025-09-24 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_servicepackage_addons_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='serviceproviderprofile',
            name='total_reviews',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='about_description',
            field=models.TextField(blank=True, verbose_name='About Description'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='current_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Current Location'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='education_institution',
            field=models.CharField(blank=True, max_length=200, verbose_name='Education Institution'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='education_years',
            field=models.CharField(blank=True, help_text='e.g., 2005-2009', max_length=20, verbose_name='Education Years'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hourly Rate'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Is Online'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='is_top_master',
            field=models.BooleanField(default=False, verbose_name='Top Master'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='languages',
            field=models.JSONField(default=list, help_text='List of languages spoken', verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Seen'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='response_time_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Response Time (hours)'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='work_experience_start_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Work Experience Start Year'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('name', models.CharField(max_length=200, verbose_name='Certificate Name')),
                ('issuing_organization', models.CharField(max_length=200, verbose_name='Issuing Organization')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Certificate Number')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('certificate_file', models.FileField(blank=True, upload_to='certificates/', verbose_name='Certificate File')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.serviceproviderprofile')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='MasterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Skill Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.servicecategory')),
            ],
            options={
                'verbose_name': 'Master Skill',
                'verbose_name_plural': 'Master Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('title', models.CharField(max_length=200, verbose_name='Work Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='portfolio_images/', verbose_name='Portfolio Image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Example')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='users.serviceproviderprofile')),
                ('skill_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='users.masterskill')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Profession Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='core.servicecategory')),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Professions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='users.profession'),
        ),
        migrations.CreateModel(
            name='ProviderStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_jobs_completed', models.PositiveIntegerField(default=0, verbose_name='Total Jobs Completed')),
                ('on_time_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='On Time Percentage')),
                ('repeat_customer_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Repeat Customer Percentage')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Average Rating')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Total Reviews')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='users.serviceproviderprofile')),
            ],
            options={
                'verbose_name': 'Provider Statistics',
                'verbose_name_plural': 'Provider Statistics',
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20, verbose_name='Proficiency Level')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('is_primary_skill', models.BooleanField(default=False, verbose_name='Primary Skill')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_skills', to='users.serviceproviderprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='users.masterskill')),
            ],
            options={
                'verbose_name': 'Service Provider Skill',
                'verbose_name_plural': 'Service Provider Skills',
                'unique_together': {('service_provider', 'skill')},
            },
        ),
    ]
