from django.urls import path

from .api.views import (
    AdvancedUserProfileRetrieveUpdateAPIView,
    CertificateListCreateAPIView,
    CertificateRetrieveUpdateDestroyAPIView,
    ClientProfileCreateAPIView,
    ClientProfileRetrieveUpdateAPIView,
    MasterSkillListAPIView,
    PortfolioItemListCreateAPIView,
    PortfolioItemRetrieveUpdateDestroyAPIView,
    ProfessionListAPIView,
    ProviderStatisticsRetrieveAPIView,
    ServiceProviderProfileCreateAPIView,
    ServiceProviderProfileRetrieveUpdateAPIView,
    ServiceProviderRetrieveAPIView,
    ServiceProviderSkillAPIView,
    UpdateOnlineStatusAPIView,
    GetUserRatingAPIView,
)

app_name = "users"

urlpatterns = [
    path(
        "api/v1/users/my/profile/advanced/",
        AdvancedUserProfileRetrieveUpdateAPIView.as_view(),
        name="my-profile-retrieve-update",
    ),
    path(
        "api/v1/users/my/client/create/",
        ClientProfileCreateAPIView.as_view(),
        name="my-client-create",
    ),
    path(
        "api/v1/users/my/client/",
        ClientProfileRetrieveUpdateAPIView.as_view(),
        name="my-client-retrieve-update",
    ),
    path(
        "api/v1/users/my/provider/create",
        ServiceProviderProfileCreateAPIView.as_view(),
        name="my-provider-create",
    ),
    path(
        "api/v1/users/my/provider/",
        ServiceProviderProfileRetrieveUpdateAPIView.as_view(),
        name="my-provider-retrieve-update",
    ),
    path(
        "api/v1/users/my/statistics/",
        ProviderStatisticsRetrieveAPIView.as_view(),
        name="my-statistics-retrieve",
    ),
    path(
        "api/v1/users/my/skills/",
        ServiceProviderSkillAPIView.as_view(),
        name="my-skills-list-create",
    ),
    path(
        "api/v1/users/my/portfolio/",
        PortfolioItemListCreateAPIView.as_view(),
        name="my-portfolio-list-create",
    ),
    path(
        "api/v1/users/my/portfolio/<int:pk>/",
        PortfolioItemRetrieveUpdateDestroyAPIView.as_view(),
        name="my-portfolio-retrieve-update-destroy",
    ),
    path(
        "api/v1/users/my/certificates/",
        CertificateListCreateAPIView.as_view(),
        name="my-certificates-list-create",
    ),
    path(
        "api/v1/users/my/certificates/<int:pk>/",
        CertificateRetrieveUpdateDestroyAPIView.as_view(),
        name="my-certificate-retrieve-update-destroy",
    ),
    # Reference Data (Public)
    path(
        "api/v1/users/skills/", MasterSkillListAPIView.as_view(), name="skills-list"
    ),
    path(
        "api/v1/users/professions/",
        ProfessionListAPIView.as_view(),
        name="professions-list",
    ),
    path(
        "api/v1/users/providers/<int:pk>/details/",
        ServiceProviderRetrieveAPIView.as_view(),
        name="provider-retrieve",
    ),
    path(
        "api/v1/users/my/online-status/",
        UpdateOnlineStatusAPIView.as_view(),
        name="update-online-status",
    ),
    path(
        "api/v1/users/<int:pk>/rating/",
        GetUserRatingAPIView.as_view(),
        name="get-user-rating",
    ),
]
