# Generated by Django 5.0.2 on 2025-06-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_post_content_type_post_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VimeoUrlCacheModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vimeo_link', models.URLField(max_length=1024, verbose_name='Link')),
                ('playable_video_link', models.URLField(max_length=1024, verbose_name='Playable Link')),
                ('expire_time', models.DateTimeField(verbose_name='Expiration time')),
            ],
            options={
                'verbose_name': 'Vimeo Link Cache',
                'verbose_name_plural': 'Vimeo Link Caches',
            },
        ),
        migrations.CreateModel(
            name='TemplateComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the component template', max_length=100, verbose_name='Title')),
                ('content', models.TextField(help_text='Template content for the component', verbose_name='Content')),
                ('component_type', models.CharField(editable=False, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('posts', models.ManyToManyField(blank=True, help_text='Posts that use this component template', related_name='component_templates', to='posts.post', verbose_name='Posts')),
            ],
            options={
                'verbose_name': 'Component Template',
                'verbose_name_plural': 'Component Templates',
            },
        ),
    ]
