# Generated by Django 5.0.2 on 2025-06-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_templatecomponent_component_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProtectedAttachment',
        ),
    ]
