# Generated by Django 5.0.2 on 2025-06-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_attachment_original_name'),
        ('resources', '0003_delete_protectedattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vimeourlcachemodel',
            name='attchment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vimeo_link_cache', to='attachments.attachment', verbose_name='Attachment'),
        ),
    ]
