# Generated by Django 5.0.2 on 2025-06-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_vimeourlcachemodel_attchment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vimeourlcachemodel',
            name='attchment',
        ),
    ]
