# Generated by Django 5.0.2 on 2025-09-24 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepackage',
            name='addons',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='supportfaq',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='core.language'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.DeleteModel(
            name='ServiceAddon',
        ),
        migrations.DeleteModel(
            name='ServicePackage',
        ),
    ]
