# Generated by Django 5.0.2 on 2025-09-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesubcategory',
            name='required_materials',
            field=models.JSONField(blank=True, default=list, verbose_name='Required Materials'),
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='required_tools',
            field=models.JSONField(blank=True, default=list, verbose_name='Required Tools'),
        ),
    ]
