# Generated by Django 5.0.2 on 2025-09-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_servicepackage_addons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.CharField(blank=True, max_length=80, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='slug',
            field=models.CharField(blank=True, max_length=80, unique=True, verbose_name='Slug'),
        ),
    ]
