# Generated by Django 5.0.2 on 2025-10-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='restored_at',
        ),
    ]
