# Generated by Django 5.0.2 on 2025-08-26 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('category', models.CharField(choices=[('greeting', 'Greeting'), ('order_update', 'Order Update'), ('support', 'Support'), ('general', 'General')], max_length=50, verbose_name='Category')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Template Content')),
                ('variables', models.JSONField(default=list, verbose_name='Template Variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Usage Count')),
            ],
            options={
                'verbose_name': 'Chat Template',
                'verbose_name_plural': 'Chat Templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('system', 'System Message'), ('order_update', 'Order Update')], default='text', max_length=20, verbose_name='Message Type')),
                ('content', models.TextField(verbose_name='Message Content')),
                ('attachment_url', models.URLField(blank=True, verbose_name='Attachment URL')),
                ('attachment_name', models.CharField(blank=True, max_length=200, verbose_name='Attachment Name')),
                ('attachment_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Attachment Size (bytes)')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.chatmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file_type', models.CharField(max_length=50, verbose_name='File Type')),
                ('file_size', models.PositiveIntegerField(verbose_name='File Size (bytes)')),
                ('file_url', models.URLField(verbose_name='File URL')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME Type')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='Thumbnail URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public File')),
                ('access_token', models.CharField(blank=True, max_length=255, verbose_name='Access Token')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatmessage')),
            ],
            options={
                'verbose_name': 'Chat Attachment',
                'verbose_name_plural': 'Chat Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('inappropriate_content', 'Inappropriate Content'), ('fake_information', 'Fake Information'), ('other', 'Other')], max_length=50, verbose_name='Report Reason')),
                ('description', models.TextField(verbose_name='Report Description')),
                ('evidence', models.JSONField(default=list, verbose_name='Evidence')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('action_taken', models.TextField(blank=True, verbose_name='Action Taken')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reported_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.chatmessage')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Report',
                'verbose_name_plural': 'Chat Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Chat Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Message At')),
                ('chat_type', models.CharField(choices=[('order_chat', 'Order Chat'), ('support_chat', 'Support Chat'), ('general_chat', 'General Chat')], default='order_chat', max_length=20, verbose_name='Chat Type')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='orders.order')),
                ('participants', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('new_message', 'New Message'), ('mention', 'Mention'), ('order_update', 'Order Update'), ('system', 'System Notification')], max_length=20, verbose_name='Notification Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('sent_via', models.CharField(choices=[('push', 'Push Notification'), ('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App')], default='in_app', max_length=20, verbose_name='Sent Via')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to=settings.AUTH_USER_MODEL)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat.chatroom')),
            ],
            options={
                'verbose_name': 'Chat Notification',
                'verbose_name_plural': 'Chat Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False, verbose_name='Online')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Last Seen')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='Unread Messages')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Notifications Enabled')),
                ('mute_until', models.DateTimeField(blank=True, null=True, verbose_name='Mute Until')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participant_status', to=settings.AUTH_USER_MODEL)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_status', to='chat.chatroom')),
            ],
            options={
                'verbose_name': 'Chat Participant',
                'verbose_name_plural': 'Chat Participants',
                'unique_together': {('chat_room', 'user')},
            },
        ),
    ]
