# Generated by Django 5.0.2 on 2025-09-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='attachment_url',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, upload_to='chat_attachments/', verbose_name='Attachment'),
        ),
    ]
