# Generated by Django 5.0.2 on 2025-10-02 20:15

import django.db.models.deletion
import utils.abstract_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('moderator', 'Moderator')], default='member', max_length=20, verbose_name='Role')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Last Seen')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='Unread Messages')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Notifications Enabled')),
                ('mute_until', models.DateTimeField(blank=True, null=True, verbose_name='Mute Until')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participant_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Participant',
                'verbose_name_plural': 'Chat Participants',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('title', utils.abstract_models.TitleField(max_length=100, verbose_name='Title')),
                ('is_active', utils.abstract_models.ActiveField(default=True, verbose_name='Active')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Message At')),
                ('chat_type', models.CharField(choices=[('job_chat', 'Job Chat'), ('support_chat', 'Support Chat'), ('general_chat', 'General Chat')], default='job_chat', max_length=20, verbose_name='Chat Type')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='jobs.job')),
                ('participants', models.ManyToManyField(related_name='chat_rooms', through='chats.ChatParticipant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_status', to='chats.chatroom'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restored at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('system', 'System Message'), ('order_update', 'Order Update')], default='text', max_length=20, verbose_name='Message Type')),
                ('content', models.TextField(verbose_name='Message Content')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('attachments', models.ManyToManyField(blank=True, related_name='chat_messages', to='attachments.attachment')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chats.chatmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chatroom')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('chat_room', 'user')},
        ),
    ]
