# Generated by Django 5.0.2 on 2025-09-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentProvider',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='terms_conditions',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='processor_response',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='stripewebhookevent',
            name='retry_count',
        ),
        migrations.AddField(
            model_name='invoice',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Platform Fee'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Charge ID'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Payment Intent ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='USD', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('digital_wallet', 'Digital Wallet')], max_length=20, verbose_name='Method Type'),
        ),
    ]
