// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvCQs6pNRp0EmzPKd2XawGIH3HJO3UGes',
    appId: '1:1026990413187:web:bf1e810ce8593ae38412b6',
    messagingSenderId: '1026990413187',
    projectId: 'master-kg-a9ffe',
    authDomain: 'master-kg-a9ffe.firebaseapp.com',
    storageBucket: 'master-kg-a9ffe.firebasestorage.app',
    measurementId: 'G-SD5YD7W3Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIm_I46Ll2VPYO0f4tEt3kl9NCfCo6TJM',
    appId: '1:1026990413187:android:e5ce728bfd5315fe8412b6',
    messagingSenderId: '1026990413187',
    projectId: 'master-kg-a9ffe',
    authDomain: 'master-kg-a9ffe.firebaseapp.com',
    storageBucket: 'master-kg-a9ffe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCufdEjKExhjtKrvNaLkhxfrf3_-w0ig2Y',
    appId: '1:1026990413187:ios:841334cf46d766b68412b6',
    messagingSenderId: '1026990413187',
    projectId: 'master-kg-a9ffe',
    authDomain: 'master-kg-a9ffe.firebaseapp.com',
    storageBucket: 'master-kg-a9ffe.firebasestorage.app',
    iosBundleId: 'com.masterkg.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCufdEjKExhjtKrvNaLkhxfrf3_-w0ig2Y',
    appId: '1:1026990413187:ios:cd4605c28c7d66d98412b6',
    messagingSenderId: '1026990413187',
    projectId: 'master-kg-a9ffe',
    authDomain: 'master-kg-a9ffe.firebaseapp.com',
    storageBucket: 'master-kg-a9ffe.firebasestorage.app',
    iosBundleId: 'com.masterkg.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvCQs6pNRp0EmzPKd2XawGIH3HJO3UGes',
    appId: '1:1026990413187:web:bf1e810ce8593ae38412b6',
    messagingSenderId: '1026990413187',
    projectId: 'master-kg-a9ffe',
    authDomain: 'master-kg-a9ffe.firebaseapp.com',
    storageBucket: 'master-kg-a9ffe.firebasestorage.app',
    measurementId: 'G-SD5YD7W3Y6',
  );
}
