name: CI/CD Pipeline

on:
    push:
        branches:
            - master

env:
    SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
    test:
        name: Run Production Tests
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:15
                env:
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: test_db
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

            redis:
                image: redis:7-alpine
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 6379:6379

        steps: 
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: check directory
              run: ls -al
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - name: Install Requirements
              run: |
                cd backend
                python -m pip install --upgrade pip
                pip install -r requirements.prod.txt
                pip install coverage
            - name: Set Up Environment
              run: |
                echo "SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV
                echo "POSTGRES_DB=test_db" >> $GITHUB_ENV
                echo "POSTGRES_USER=postgres" >> $GITHUB_ENV
                echo "POSTGRES_PASSWORD=postgres" >> $GITHUB_ENV
                echo "POSTGRES_HOST=localhost" >> $GITHUB_ENV
                echo "POSTGRES_PORT=5432" >> $GITHUB_ENV
                echo "REDIS_HOST=localhost" >> $GITHUB_ENV
                echo "REDIS_PORT=6379" >> $GITHUB_ENV
                echo "DEBUG=True" >> $GITHUB_ENV
                echo "DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1" >> $GITHUB_ENV
                echo "DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost,http://127.0.0.1" >> $GITHUB_ENV
                echo "FIREBASE_CREDENTIALS_PATH=/tmp/firebase-test.json" >> $GITHUB_ENV
                echo "USE_NGINX=false" >> $GITHUB_ENV
            
            - name: Create Real Firebase Credentials
              run: |
                echo '${{ secrets.FIREBASE_CREDENTIALS_JSON }}' > /tmp/firebase-test.json
            - name: Wait for database
              run: |
                while ! pg_isready -h localhost -p 5432 -U postgres; do
                  echo "Waiting for PostgreSQL..."
                  sleep 2
                done
            - name: Run Test
              run: |
                cd backend
                python manage.py migrate --settings=backend.settings.prod
                coverage run --include='**/models.py,**/views.py,**/serializers.py' --omit='env/*,*/opt/*,job_portal/apps/users/api/views.py,job_portal/apps/users/models.py,utils/crud_base/views.py,utils/serializers.py' manage.py test --settings=backend.settings.prod
                coverage report -m --fail-under=70

    build:
        name: Build & Publish Production Images
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: check directory
              run: ls -al
            - name: Set Up Environment
              run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV
            - name: Docker login
              run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin docker.io
            - name: Set Docker BuildKit
              run: export DOCKER_BUILDKIT=1
            - name: Build Django Docker Image
              run: |
                  cd backend
                  docker build -t ${{ secrets.REGISTRY_USER }}/${{ secrets.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f Dockerfile.prod .
                  docker push ${{ secrets.REGISTRY_USER }}/${{ secrets.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            - name: Build Nginx Docker Image
              run: |
                  cd nginx
                  docker build -t ${{ secrets.REGISTRY_USER }}/${{ secrets.IMAGE_NAME }}-nginx:${{ env.IMAGE_TAG }} .
                  docker push ${{ secrets.REGISTRY_USER }}/${{ secrets.IMAGE_NAME }}-nginx:${{ env.IMAGE_TAG }}

    deploy:
        name: Deploy to Production VPS
        runs-on: ubuntu-latest
        needs: build
        if: github.ref == 'refs/heads/master'
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Install SSH client
              run: sudo apt-get install openssh-client
            - name: Set Up Environment
              run: |
                echo "DJANGO_SETTINGS_MODULE=${{ secrets.PROD_DJANGO_SETTINGS_MODULE }}" >> $GITHUB_ENV
                echo "PORT=8000" >> $GITHUB_ENV
                echo "CONTAINER_NAME=kg-job-portal" >> $GITHUB_ENV
                echo "IMAGE_TAG=latest" >> $GITHUB_ENV
                echo "COMPOSE_FILE=docker-compose.prod.yml" >> $GITHUB_ENV

            - name: Setup SSH passphrase
              run: |
                ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                echo 'echo ${{ secrets.VPS_SSH_PASSPHRASE }}' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
                echo "${{ secrets.VPS_SSH_KEY }}" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null
            - name: Deploy to VPS
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USERNAME }}
                key: ${{ secrets.VPS_SSH_KEY }}
                passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
                script: |
                    # Navigate to project directory
                    cd /opt/kg-job-portal
                    
                    # Pull latest changes
                    git pull origin master
                    
                    # Create backup of current deployment
                    if [ -d "backup" ]; then
                        rm -rf backup
                    fi
                    mkdir backup
                    if [ -d "current" ]; then
                        cp -r current/* backup/
                    fi
                    
                    # Login to Docker registry
                    echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | sudo docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin docker.io
                    
                    # Stop current services
                    sudo docker-compose -f ${{ env.COMPOSE_FILE }} down
                    
                    # Pull latest images
                    sudo docker-compose -f ${{ env.COMPOSE_FILE }} pull
                    
                    # Start services
                    sudo docker-compose -f ${{ env.COMPOSE_FILE }} up -d
                    
                    # Wait for services to be healthy
                    sleep 30
                    
                    # Check service health
                    if sudo docker-compose -f ${{ env.COMPOSE_FILE }} ps | grep -q "unhealthy"; then
                        echo "Services are unhealthy, rolling back..."
                        sudo docker-compose -f ${{ env.COMPOSE_FILE }} down
                        if [ -d "backup" ]; then
                            cp -r backup/* current/
                            sudo docker-compose -f ${{ env.COMPOSE_FILE }} up -d
                        fi
                        exit 1
                    fi
                    
                    # Run database migrations
                    sudo docker-compose -f ${{ env.COMPOSE_FILE }} exec -T backend python manage.py migrate --noinput --settings=backend.settings.prod
                    
                    # Collect static files
                    sudo docker-compose -f ${{ env.COMPOSE_FILE }} exec -T backend python manage.py collectstatic --noinput --settings=backend.settings.prod
                    
                    # Clear cache
                    sudo docker-compose -f ${{ env.COMPOSE_FILE }} exec -T backend python manage.py clearcache --settings=backend.settings.prod
                    
                    # Health check
                    if curl -f http://localhost:${{ env.PORT }}/health/; then
                        echo "Deployment successful!"
                    else
                        echo "Health check failed, rolling back..."
                        sudo docker-compose -f ${{ env.COMPOSE_FILE }} down
                        if [ -d "backup" ]; then
                            cp -r backup/* current/
                            sudo docker-compose -f ${{ env.COMPOSE_FILE }} up -d
                        fi
                        exit 1
                    fi
